dataset_name: "myst"
train_embeddings_path: "/home/embeddings/embeddings_train.npy"
train_label1_path: "/home/embeddings/speaker_label_train.npy"
train_label2_path: "/home/embeddings/task_label_train.npy"
